### PR TITLE
Migration to Rust deps and Yarn

### PR DESCRIPTION
**Pull request by Mikescops**
This PR tries to solve multiple issues with dependencies we have:
- remove keytar as it is now unmaintained (GitHub stopped the Atom project and all related dependencies)
- move argon2 to Rust (faster and also no more node-gyp)
- moved to yarn to be able to support multiple architectures
- rework the different integrations of the modules in the code

### CODE REVIEW

**Comment by Mikescops** [comment]
I tested on Windows and it works well except for the reported clipboardy bug 

> /snapshot/dashlane-cli/node_modules/clipboardy/fallbacks/windows/clipboard_x86_64.exe ENOENT 

but this is already reported in #45

**Comment by jboillot** [comment]
Re-add `package-lock.json` file.

**Comment by jboillot** [comment]
I think we should correct `README.md` file about how to install dependencies, from `npm ci` to `yarn install --frozen-lockfile`.
Can you confirm that?

**Review by jboillot — APPROVED** [review]

**Comment by Mikescops** [comment]
Closes #72

**Pull request merged**
